#!/bin/bash
# Copyright 2021 Gavin Pease

source .env
mysql -u $SQLSPRINKLER_USER --password=$SQLSPRINKLER_PASS -h $SQLSPRINKLER_SQL_HOST -e "
CREATE DATABASE IF NOT EXISTS $SQLSPRINKLER_DB;
USE $SQLSPRINKLER_DB;
    CREATE TABLE IF NOT EXISTS Systems(
    Name TEXT NOT NULL,
    GPIO INT NOT NULL DEFAULT 13,
    Time INT NOT NULL DEFAULT 10,
    id INT NOT NULL AUTO_INCREMENT,
    Enabled BOOLEAN NOT NULL DEFAULT 1,
    Autooff BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
  );
  CREATE TABLE IF NOT EXISTS  Enabled(enabled BOOLEAN NOT NULL DEFAULT 0, UNIQUE(enabled));
"
